// worker/src/api/v1/randomLocalPart.ts
// 深模块(叶): v1 随机 localPart 生成 — 字典名 + CSPRNG 后缀 (PR#42 CR-2)
// Interface: generateRandomLocalPart · RANDOM_SUFFIX_LENGTH
// Implementation: 纯函数 + Web Crypto getRandomValues, 零依赖(node --test 可直接加载)
// 字典数组自 routes/mailboxes.ts 原样迁移(250 first × 250 last), 内容逐字未改

import { isValidLocalPart } from "./localPart.ts";

const firstNames = [
  // 男性名
  "james",
  "john",
  "robert",
  "michael",
  "william",
  "david",
  "richard",
  "joseph",
  "thomas",
  "charles",
  "christopher",
  "daniel",
  "matthew",
  "anthony",
  "mark",
  "donald",
  "steven",
  "paul",
  "andrew",
  "joshua",
  "kenneth",
  "kevin",
  "brian",
  "george",
  "timothy",
  "ronald",
  "edward",
  "jason",
  "jeffrey",
  "ryan",
  "jacob",
  "gary",
  "nicholas",
  "eric",
  "jonathan",
  "stephen",
  "larry",
  "justin",
  "scott",
  "brandon",
  "benjamin",
  "samuel",
  "raymond",
  "gregory",
  "frank",
  "alexander",
  "patrick",
  "jack",
  "dennis",
  "jerry",
  "aaron",
  "alan",
  "adam",
  "andy",
  "barry",
  "bill",
  "bob",
  "brad",
  "brett",
  "brent",
  "bruce",
  "bryan",
  "chad",
  "charlie",
  "chris",
  "clark",
  "clay",
  "cliff",
  "clint",
  "craig",
  "dale",
  "dan",
  "darrell",
  "dave",
  "derek",
  "devin",
  "doug",
  "duane",
  "dustin",
  "dwight",
  "earl",
  "edgar",
  "eli",
  "elliot",
  "ethan",
  "evan",
  "finn",
  "gabriel",
  "henry",
  "ian",
  "jake",
  "joel",
  "julian",
  "karl",
  "lane",
  "leo",
  "liam",
  "logan",
  "lucas",
  "mason",
  "max",
  "miles",
  "neil",
  "noah",
  "oliver",
  "pete",
  "ray",
  "reid",
  "ross",
  "sean",
  "seth",
  "todd",
  "troy",
  "wade",
  "will",
  "calvin",
  "claude",
  "felix",
  "floyd",
  "glen",
  "grant",
  "hank",
  "herb",
  "homer",
  "horace",
  "ivan",
  "jerome",
  "lance",
  "lloyd",
  "marshall",
  // 女性名
  "mary",
  "patricia",
  "jennifer",
  "linda",
  "barbara",
  "elizabeth",
  "susan",
  "jessica",
  "sarah",
  "karen",
  "lisa",
  "nancy",
  "betty",
  "margaret",
  "sandra",
  "ashley",
  "emily",
  "kimberly",
  "donna",
  "carol",
  "michelle",
  "dorothy",
  "amanda",
  "melissa",
  "deborah",
  "stephanie",
  "rebecca",
  "sharon",
  "laura",
  "cynthia",
  "kathleen",
  "amy",
  "angela",
  "shirley",
  "anna",
  "brenda",
  "pamela",
  "emma",
  "nicole",
  "helen",
  "samantha",
  "katherine",
  "christine",
  "debra",
  "rachel",
  "carolyn",
  "janet",
  "catherine",
  "maria",
  "heather",
  "sophia",
  "olivia",
  "ava",
  "isabella",
  "mia",
  "abigail",
  "madison",
  "chloe",
  "ella",
  "avery",
  "scarlett",
  "grace",
  "lily",
  "aria",
  "riley",
  "zoey",
  "nora",
  "hazel",
  "aurora",
  "savannah",
  "brooklyn",
  "leah",
  "zoe",
  "stella",
  "natalie",
  "eva",
  "claire",
  "ellie",
  "maya",
  "piper",
  "victoria",
  "lucy",
  "paisley",
  "skylar",
  "camila",
  "penelope",
  "layla",
  "hailey",
  "luna",
  "amber",
  "april",
  "beth",
  "brooke",
  "dana",
  "dawn",
  "diana",
  "fiona",
  "gail",
  "holly",
  "jade",
  "jan",
  "joan",
  "joyce",
  "june",
  "kate",
  "kay",
  "kim",
  "leigh",
  "lynn",
  "molly",
  "paige",
  "ruth",
  "tara",
  "vera",
  "wendy",
  "abby",
  "alice",
  "anne",
  "bea",
  "rose",
];

const lastNames = [
  "smith",
  "johnson",
  "williams",
  "brown",
  "jones",
  "garcia",
  "miller",
  "davis",
  "wilson",
  "taylor",
  "anderson",
  "thomas",
  "jackson",
  "white",
  "harris",
  "martin",
  "thompson",
  "young",
  "allen",
  "king",
  "wright",
  "scott",
  "torres",
  "nguyen",
  "hill",
  "flores",
  "green",
  "adams",
  "nelson",
  "baker",
  "hall",
  "rivera",
  "campbell",
  "mitchell",
  "carter",
  "roberts",
  "gomez",
  "phillips",
  "evans",
  "turner",
  "diaz",
  "parker",
  "cruz",
  "edwards",
  "collins",
  "reyes",
  "stewart",
  "morris",
  "morales",
  "murphy",
  "cook",
  "rogers",
  "gutierrez",
  "ortiz",
  "morgan",
  "cooper",
  "peterson",
  "bailey",
  "reed",
  "kelly",
  "howard",
  "ramos",
  "kim",
  "cox",
  "ward",
  "richardson",
  "watson",
  "brooks",
  "chavez",
  "wood",
  "james",
  "bennett",
  "gray",
  "mendoza",
  "ruiz",
  "hughes",
  "price",
  "alvarez",
  "castillo",
  "sanders",
  "patel",
  "myers",
  "long",
  "ross",
  "foster",
  "jimenez",
  "powell",
  "jenkins",
  "perry",
  "russell",
  "sullivan",
  "bell",
  "coleman",
  "butler",
  "henderson",
  "barnes",
  "gonzalez",
  "fisher",
  "vasquez",
  "simmons",
  "romero",
  "jordan",
  "patterson",
  "alexander",
  "hamilton",
  "graham",
  "reynolds",
  "griffin",
  "wallace",
  "moreno",
  "west",
  "cole",
  "hayes",
  "bryant",
  "herrera",
  "gibson",
  "ellis",
  "tran",
  "medina",
  "aguilar",
  "stevens",
  "murray",
  "ford",
  "castro",
  "marshall",
  "owens",
  "harrison",
  "fernandez",
  "mcdonald",
  "woods",
  "kennedy",
  "wells",
  "vargas",
  "henry",
  "chen",
  "freeman",
  "webb",
  "tucker",
  "guzman",
  "burns",
  "crawford",
  "olson",
  "simpson",
  "porter",
  "hunter",
  "gordon",
  "mendez",
  "silva",
  "shaw",
  "snyder",
  "mason",
  "munoz",
  "hunt",
  "hicks",
  "holmes",
  "palmer",
  "wagner",
  "black",
  "robertson",
  "boyd",
  "stone",
  "salazar",
  "fox",
  "warren",
  "mills",
  "meyer",
  "rice",
  "schmidt",
  "garza",
  "daniels",
  "ferguson",
  "nichols",
  "stephens",
  "soto",
  "weaver",
  "ryan",
  "gardner",
  "payne",
  "grant",
  "dunn",
  "kelley",
  "spencer",
  "hawkins",
  "arnold",
  "pierce",
  "stevenson",
  "lawson",
  "bishop",
  "byrd",
  "christensen",
  "mann",
  "carr",
  "lee",
  "harvey",
  "walsh",
  "cross",
  "lane",
  "klein",
  "parks",
  "sharp",
  "berry",
  "morrow",
  "powers",
  "holt",
  "terry",
  "bond",
  "cannon",
  "hart",
  "dean",
  "day",
  "lowe",
  "rios",
  "leon",
  "malone",
  "french",
  "hammond",
  "moss",
  "horton",
  "waters",
  "rhodes",
  "bass",
  "quinn",
  "hardy",
  "marsh",
  "howell",
  "barker",
  "larson",
  "norris",
  "dawson",
  "fletcher",
  "watts",
  "strickland",
  "horne",
  "burnett",
  "pope",
  "barber",
  "caldwell",
  "gilbert",
  "patton",
  "hutchinson",
  "bowers",
  "barton",
  "rush",
  "love",
  "hanson",
  "graves",
  "alvarado",
  "zimmerman",
  "mcbride",
  "luna",
];

// —— 字典基座构建(自原 generateRandomLocalPart 迁移; Math.random 仅用于选型, 非凭证) ——
function buildBase(): string {
  const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
  // 模拟出生年（1960–2005）的两位数后缀，如 84、92、03
  const yearSuffix = (): string =>
    String((Math.floor(Math.random() * 46) + 60) % 100).padStart(2, "0");
  const num2 = (): string =>
    String(Math.floor(Math.random() * 100)).padStart(2, "0");

  const first = pick(firstNames);
  const last = pick(lastNames);
  const f = first[0];

  // 7 种命名模式，随机选取一种
  const patterns: (() => string)[] = [
    () => `${first}.${last}`, // 示例: john.smith（点分隔）
    () => `${first}_${last}`, // 示例: john_smith（下划线）
    () => `${first}${last}`, // 示例: johnsmith（直接拼接）
    () => `${f}.${last}`, // 示例: j.smith（名缩写.姓）
    () => `${f}${last}`, // 示例: jsmith（名缩写+姓）
    () => `${first}${num2()}`, // 示例: john84（名+两位数字）
    () => `${first}.${last}${yearSuffix()}`, // 示例: john.smith92（点分隔+年份后缀）
  ];

  return pick(patterns)();
}

/** 随机后缀长度: 36^6 ≈ 21.8 亿组合, 使字典组合空间不可枚举 */
export const RANDOM_SUFFIX_LENGTH = 6;

const SUFFIX_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";

/**
 * 生成 "字典基座.六位CSPRNG后缀" 形态的 localPart。
 * 前半保留真人命名可读性, 后半由 crypto.getRandomValues 提供抗枚举熵。
 * 兜底断言: 超长或非法立即抛错而非静默产出坏地址。
 */
export function generateRandomLocalPart(): string {
  const base = buildBase();
  const bytes = new Uint8Array(RANDOM_SUFFIX_LENGTH);
  crypto.getRandomValues(bytes);
  let suffix = "";
  for (let i = 0; i < RANDOM_SUFFIX_LENGTH; i++) {
    suffix += SUFFIX_ALPHABET[bytes[i] % SUFFIX_ALPHABET.length];
  }
  const value = base + "." + suffix;
  if (!isValidLocalPart(value)) {
    throw new Error(`生成的 localPart 未通过格式闸口: ` + value);
  }
  return value;
}
/** 冲突重试上限: 36^6 空间下连续 5 次撞车的概率约 1e-53, 视为字典耗尽 */
export const MAX_GENERATE_ATTEMPTS = 5;

/**
 * 生成不与现有地址冲突的随机 localPart。
 * @param exists 探测候选是否已存在(调用方注入查重实现), 命中返回 true
 * @returns 通过探测的唯一 localPart
 * @throws 超过 MAX_GENERATE_ATTEMPTS 次仍冲突(调用方映射 409 CONFLICT)
 */
export async function generateUniqueLocalPart(
  exists: (candidate: string) => Promise<boolean>,
): Promise<string> {
  for (let attempt = 0; attempt < MAX_GENERATE_ATTEMPTS; attempt++) {
    const candidate = generateRandomLocalPart();
    if (!(await exists(candidate))) return candidate;
  }
  throw new Error("LOCAL_PART_EXHAUSTED");
}
